dist: trusty
sudo: required
language: node_js
node_js:
  - "8.9"

matrix:
  include:
    - os: linux
      dist: trusty
      before_install: 
      - npm install
      - npm install truffle

install: 
  - ganache-cli 2>&1 /dev/null &

script:
  - truffle migrate
  - truffle test
